### ISSUE TITLE
本身有数据,求解决方法

### ISSUE THREAD

**Issue by StringKe** [edwinhuish/bootstrap-multitabs#10]
![image](https://user-images.githubusercontent.com/31089228/49266555-96aaa080-f491-11e8-9503-a6931aa6d4e1.png)
本身我这里是有内容和数据的,要想做到一行显示并切换,不是iframe的这种方式
只想做到然后这些tabs并排并且可拖动

**Comment by edwinhuish** [comment]
这个貌似不是我的代码的功能吧？

你描述不是很清晰，不知道你这些tab是如何生成的，不过你想要让他排成一行，可以参考我这个代码的CSS.
