### ISSUE TITLE
iframe 怎么自适应高度 

### ISSUE THREAD

**Issue by zlw0124** [edwinhuish/bootstrap-multitabs#14]
这一块代码怎么用
<script>
    parent.$(parent.document).data('multitabs').create({
        iframe : true,                                //指定为iframe模式，当值为false的时候，为智能模式，自动判断（内网用ajax，外网用iframe）。缺省为false。
        title : 'open by iframe',                     //标题（可选），没有则显示网址
        url : 'pages/index-2.html'                    //链接（必须），如为外链，强制为info页
    }, true);                                         //true 则激活新增的tab页
</script>

**Comment by edwinhuish** [comment]
自适应高度主要看这段css：

```
<style type="text/css">
    body,
    body.full-height-layout .wrapper,
    html{
        height: 100%;
    }
    body.full-height-layout .content-wrapper{           /*使用multitabs的wrapper*/
        height: calc(100% - 140px)                      /*减去网页header和footer的高度，AdminLTE的为140px*/
    }
</style>
```

原理是将 multitabs 的wrapper 设置为出去外包围的正确高度，并将此wrapper的所有父层都设为100%
