### ISSUE TITLE
跳转页面白屏

### ISSUE THREAD

**Issue by xumqfaith** [edwinhuish/bootstrap-multitabs#15]
`<button class="Add btn btn-success margin-r-5" onclick="window.location.href='infoAdd.html'">添加</button>
`
在一个iframe页面中有一个跳转页面的事件
有时跳转页面的时候，页面会白屏，但是看XHR,ajax请求已经发起且请求成功，甚至在Elements里面DOM已经加载出来了，就是显示不出来。
刷新一下，打开F12，页面又会显示出来。请问iframe内跳转页面到底应该用什么？谢谢！

**Comment by edwinhuish** [comment]
你这个。。。貌似不是我的mutitabs的使用方式吧？ 或者请附上完整示例。

**Comment by xumqfaith** [comment]
`var multitabs = $('#content_wrapper').multitabs({
            init: [
                {
                    type: 'main',
                    title: '首页',
                    iframe: true,
                    url: 'pages/index.html'
                }
            ]
        });`
比如，有个tab是index..html,在index.html中，有个按钮，点击 window.location.href 跳转进入info.html，这时会出现白屏，概率有时该挺高的。

**Comment by edwinhuish** [comment]
> `var multitabs = $('#content_wrapper').multitabs({ init: [ { type: 'main', title: '首页', iframe: true, url: 'pages/index.html' } ] });`
> 比如，有个tab是index..html,在index.html中，有个按钮，点击 window.location.href 跳转进入info.html，这时会出现白屏，概率有时该挺高的。

不明白，你为什么要用 ```  window.location.href ``` 呢？ 请给出具体具体实例。

**Comment by xumqfaith** [comment]
简单来说，在一个iframe内有页面A，此时我想进入B页面，但我并不想开一个新的Tab，只在当前的iframe内直接切换页面，请问该怎么切换？

**Comment by edwinhuish** [comment]
如果完全不想要tab页，将 ``` maxTabs ``` 设置为1。

如果是仅仅那一个页面在原有的tab页打开，那能做的只能是封装一个函数，点击先关闭原tab，再打开新tab。
