### ISSUE TITLE
Find a way to save pivot table along with some attributes 

### ISSUE THREAD

**Issue by matondojoao** [edwinhuish/bootstrap-multitabs#17]
hello sir i am sorry i found you in https://github.com/z-song/laravel-admin/issues/395 could you help me please to Find a way to save pivot table along with some attributes  i really need this to my final project help me please give me some examples

**Comment by edwinhuish** [comment]
you should ask in laravel-admin

**Comment by matondojoao** [comment]
i asked but they didn't reply, help me please

**Comment by matondojoao** [comment]
i asked but they didn't reply, help me please @edwinhuish
