### ISSUE TITLE
移动端tab隐藏问题

### ISSUE THREAD

**Issue by pihc** [edwinhuish/bootstrap-multitabs#2]
1.移动端隐藏了tab的展示，但是dom里和pc端一样，点击一个菜单，增加一个iframe或者一个div；在菜单很多的情况下，用户点击了很多菜单，对于移动端内存和流量的消耗还是挺大的，毕竟不像pc端那样可以手动清除tab,我想能不能做成new点击的菜单的内容去“替换”之前展示的内容，而不是“新增”

2.您这里给了两种展示方案，一种是iframe,一种是div。我不知道该如何选择，当然理由也是一大堆，希望您能给出点建议:sob:，我自己一直都是用iframe（遇到的问题就是，bootstrap modal 或者layer 弹窗的遮罩层没法覆盖父页面）

首先声明一下，我是一个刚入行两年的菜鸟，如有不对，请多包含:blush::blush:

**Comment by edwinhuish** [comment]
1. Multitabs主要是面向后台的管理页面，不适宜作为前台。流量方面，对于后台页面，流量是一个可以忽略的问题。而关于你所说的内存消耗，其实 Multitabs 有限制最大tab数量，这个数量你可以自己设定，超过的话，会依次替换以前的旧页面。
```
nav : {
        maxTabs : 15,                           //Max tabs number (without counting main tab), when is 1, hide the whole nav
    },
```

2. 如果你刚开始入手前端，你先考虑iframe吧，ajax容易css，js冲突。至于弹窗遮罩层问题，你需要做的是通过父层页面弹出弹窗，而不是iframe页面。

**Comment by edwinhuish** [comment]
另外，关于第一点，如果你实在纠结内存问题的话，你可以自行写一个js，手机界面每次点击菜单触发 ``` closeOthers() ``` 方法即可
